# Site settings
title: Simons thoughts
email: simonkoudijs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.2simon.nl" # the base hostname & protocol for your site
twitter_username: simonkoudijs
github_username: sunib
highlighter: rouge

# Build settings
markdown: kramdown
